spring:
  datasource:
    url: jdbc:mysql://localhost:3307/promotion
    username: user
    password: admin

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
