spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mysql:8.0.34:///test?TC_INITSCRIPT=schema.sql
    username: test
    password: test

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true

jwt:
  secret-key: 1231231231231231231231231231231231312312312312312312312312312312

front:
  url: url1, url2, url3
